//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pickles.Infrastructure.UploadJob.PASService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pas_ws", ConfigurationName="PASService.n_ws_pas_interface")]
    public interface n_ws_pas_interface {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pingReturn")]
        int ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pingReturn")]
        System.Threading.Tasks.Task<int> pingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="processmessageReturn")]
        string processmessage(string xml_dataxml_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="processmessageReturn")]
        System.Threading.Tasks.Task<string> processmessageAsync(string xml_dataxml_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getdataReturn")]
        string getdata(string xml_parametersxml_parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getdataReturn")]
        System.Threading.Tasks.Task<string> getdataAsync(string xml_parametersxml_parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="itemmanagementserviceReturn")]
        string itemmanagementservice(string as_xml_dataas_xml_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="itemmanagementserviceReturn")]
        System.Threading.Tasks.Task<string> itemmanagementserviceAsync(string as_xml_dataas_xml_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="servslifeReturn")]
        string servslife(string as_xml_dataas_xml_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="servslifeReturn")]
        System.Threading.Tasks.Task<string> servslifeAsync(string as_xml_dataas_xml_data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface n_ws_pas_interfaceChannel : Pickles.Infrastructure.UploadJob.PASService.n_ws_pas_interface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class n_ws_pas_interfaceClient : System.ServiceModel.ClientBase<Pickles.Infrastructure.UploadJob.PASService.n_ws_pas_interface>, Pickles.Infrastructure.UploadJob.PASService.n_ws_pas_interface {
        
        public n_ws_pas_interfaceClient() {
        }
        
        public n_ws_pas_interfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public n_ws_pas_interfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public n_ws_pas_interfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public n_ws_pas_interfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ping() {
            return base.Channel.ping();
        }
        
        public System.Threading.Tasks.Task<int> pingAsync() {
            return base.Channel.pingAsync();
        }
        
        public string processmessage(string xml_dataxml_data) {
            return base.Channel.processmessage(xml_dataxml_data);
        }
        
        public System.Threading.Tasks.Task<string> processmessageAsync(string xml_dataxml_data) {
            return base.Channel.processmessageAsync(xml_dataxml_data);
        }
        
        public string getdata(string xml_parametersxml_parameters) {
            return base.Channel.getdata(xml_parametersxml_parameters);
        }
        
        public System.Threading.Tasks.Task<string> getdataAsync(string xml_parametersxml_parameters) {
            return base.Channel.getdataAsync(xml_parametersxml_parameters);
        }
        
        public string itemmanagementservice(string as_xml_dataas_xml_data) {
            return base.Channel.itemmanagementservice(as_xml_dataas_xml_data);
        }
        
        public System.Threading.Tasks.Task<string> itemmanagementserviceAsync(string as_xml_dataas_xml_data) {
            return base.Channel.itemmanagementserviceAsync(as_xml_dataas_xml_data);
        }
        
        public string servslife(string as_xml_dataas_xml_data) {
            return base.Channel.servslife(as_xml_dataas_xml_data);
        }
        
        public System.Threading.Tasks.Task<string> servslifeAsync(string as_xml_dataas_xml_data) {
            return base.Channel.servslifeAsync(as_xml_dataas_xml_data);
        }
    }
}
